;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Movement.Rung",NewTagName="Movement.Run")
+GameplayTagList=(Tag="Movement",DevComment="GameplayTag that will check the character\'s movement")
+GameplayTagList=(Tag="Movement.Crouch",DevComment="Check when character is crouched")
+GameplayTagList=(Tag="Movement.Fall",DevComment="Check when character is falling")
+GameplayTagList=(Tag="Movement.Idle",DevComment="Check for if character is idle")
+GameplayTagList=(Tag="Movement.Jump",DevComment="Check for when character jumping")
+GameplayTagList=(Tag="Movement.Run",DevComment="Check for if character is running")
+GameplayTagList=(Tag="Movement.Walk",DevComment="Check for if character is walking")

